### ISSUE TITLE
Receiving BAD REQUEST after update from 3rd January 2022

### ISSUE THREAD

**Issue by magic21nrw** [thobach/MMM-MicrosoftToDo#69] opened 2022-01-04 14:15 UTC
Hi,

it seems that the last update broke something I cannot figure out what is wrong with it.

[ERROR] [MMM-MicrosoftToDo]: Error: Bad Request

This is the only log entry I receive.

Things I already checked:

1. Installed fresh Module by git clone the repository
2. npm install run 
3. restart MagicMirror
4. created new Login credentials (just to be sure but old ones worked on January 1st).

Everything else is up to date npm & node.

Any ideas where to look to find a solution?

EDIT - 15:50 pm:

I moved back to Checkout Version 9cbef27 which works - somehow the request with the rewritten part fails with my installation. Do I need more than the npm install after cloning the repository?

**Comment by spyder007** [comment] 2022-01-10 17:19
What version of MagicMirror are  you running?  You need at least 2.15 to have node-fetch installed.  However, if you're getting a bad request, it might be something in the formatting.

If you change your logging to debug level, you should see more output.

**Comment by magic21nrw** [comment] 2022-01-11 08:02
Hi,

I am running latest Magic Mirror Version from January 1st 2022 (I think it is 2.18).
Will test with debug on in the next days when I have some more spare time.

Daniel

**Comment by LemurensReise** [comment] 2022-01-13 22:00
Hi, I also have the same problem.. tried updating everything, and have the newest MM-version.

**Comment by spyder007** [comment] 2022-01-13 23:51
@LemurensReise are you able to enable MagicMirror's debug logging?

```
let config = {
	logLevel: ["DEBUG", "INFO", "LOG", "WARN", "ERROR"], 
        ....
```

**Comment by LemurensReise** [comment] 2022-01-14 10:31
@spyder007 Yes:

[ERROR] [MMM-MicrosoftToDo]: Error: Bad Request
[DEBUG] parsed data={"<link rel=stylesheet type=text/css href=https":"//www.calendarlabs.com/css/cal.css />
And the link is huge and end with this
   window._mnhandle = window._mnhandle || {}":{"params":{"   window._mNHandle.queue ":" window._mNHandle.queue || []","   medianet_versionId ":3161199,"   (function() {       var sct ":" document.createElement(script),           winObj = window.top || window,           sctHl = winObj.document.getElementsByTagName(script)[0]","       sct.type ":" text/javascript","       sct.src ":" 'https"},"val":"//contextual.media.net/einslmedianet.js?cid=8CUIZZF82&crid=372468305&size=641x481';       sct.async = async;       sctHl.parentNode.insertBefore(sct, sctHl);   })();"}}

**Comment by spyder007** [comment] 2022-01-14 11:57
Is there any logging BEFORE the MMM-MicrosoftToDo error?  The debug message above seems to be for the calendar control.

Also, can you post your config (minus your authentication pieces)?  I'm not able to reproduce this locally.

**Comment by LemurensReise** [comment] 2022-01-14 12:03
Right now, I can run the server, but when I open the localhost this is the log:
[14.01.2022 11:28.05.204] [LOG]   Create new calendarfetcher for url: https://www.calendarlabs.com/print-online-calendar.php?y=2022&m=1&v=year&wc=11&h=1&c=norway&l=no - Interval: 300000
[14.01.2022 11:28.05.240] [LOG]   Create new newsfetcher for url: https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
[14.01.2022 11:28.06.678] [ERROR] [MMM-MicrosoftToDo]: Error: Bad Request

This is my config now:

		{
			module: 'MMM-MicrosoftToDo',
			position: 'top_left',	// This can be any of the regions. Best results in left or right regions.
			header: 'To Do', // This is optional
			config: {
			  oauth2ClientSecret: '',
			  oauth2RefreshToken: '',
			  oauth2ClientId: '',
			  listName: 'ovinger', // optional parameter: if not specified displays tasks from default "Tasks" list, if specified will look for a task list with the specified name (exact spelling)
			  // Optional parameter:  see Planned Tasks Configuration
			  plannedTasks: {
				enabled: true
			  },
			  showCheckbox: true, // optional parameter: default value is true and will show a checkbox before each todo list item
			  showDueDate: false, // optional parameter: default value is false and will show the todo list items due date if it exists on the todo list item
			  dateFormat: 'ddd MMM Do [ - ]', //optional parameter: uses moment date format and the default value is 'ddd MMM Do [ - ]'
			  highlightTagColor: '#E3FF30', // optional parameter: highlight tags (#Tags) in the entry text. value can be a HTML color value
			  hideIfEmpty: false, // optional parameter: default value is false and will show the module also when the todo list is empty
			  maxWidth: 450, // optional parameter: max width in pixel, default value is 450
			  itemLimit: 200, // optional parameter: limit on the number of items to show from the list, default value is 200
			  orderBy: 'createdDate', // optional parameter: 'createdDate' - order results by creation date, 'dueDate' - order results by due date, default value is unordered, ordering by title is not supported anymore in API version 1
			  completeOnClick: true, // optional parameter: default value is false, when set to true complete task when clicking on it
			  refreshSeconds: 60, // optional parameter: every how many seconds should the list be updated from the remote service, default value is 60
			  fade: true, //optional parameter: default value is false. True will fade the list towards the bottom from the point set in the fadePoint parameter
			  fadePoint: 0.5 //optional parameter: decimal value between 0 and 1 sets the point where the fade effect will start,
			}
		},

**Comment by spyder007** [comment] 2022-01-14 12:11
So you're running in server mode and accessing via a browser?  Are there any errors in the Javascript console in the browser?

**Comment by LemurensReise** [comment] 2022-01-14 12:15
Yes, I'm setting up my frist MM.
Thses are the errors in the console: 

Refused to apply style from 'http://localhost:8080/css/custom.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Error on loading stylesheet: css/custom.css

TypeError: Cannot read properties of undefined (reading 'match')
    at MMM-MicrosoftToDo.js:130
    at Array.forEach (<anonymous>)
    at Class.getDom (MMM-MicrosoftToDo.js:54)
    at main.js:113
    at new Promise (<anonymous>)
    at updateDom (main.js:111)
    at main.js:53
    at Array.forEach (<anonymous>)
    at createDomObjects (main.js:20)
    at Object.modulesStarted (main.js:502)

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'match')
    at MMM-MicrosoftToDo.js:130
    at Array.forEach (<anonymous>)
    at Class.getDom (MMM-MicrosoftToDo.js:54)
    at main.js:113
    at new Promise (<anonymous>)
    at updateDom (main.js:111)
    at main.js:53
    at Array.forEach (<anonymous>)
    at createDomObjects (main.js:20)
    at Object.modulesStarted (main.js:502)

Refused to apply style from 'http://localhost:8080/css/custom.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by spyder007** [comment] 2022-01-14 13:07
Can you try to grab PR #70 ?

There was a very odd hidden error when the element title is null (which doesn't make sense as to why it would be null, but I haven't tracked that down).  I believe PR 70 might fix your issues

**Comment by LemurensReise** [comment] 2022-01-14 14:10
Should I replace the node_helper.js in MMM-MicrosoftToDo with the file you committed 10 days ago?

**Comment by magic21nrw** [comment] 2022-01-14 16:46
@spyder007 - Using it in Server only mode as I am running different mirrors that access the server via http.
Unfortunately getting git clone your repository with the PR #70  included does not fix the issue. 

- I know I am still not been able to post a debug log file but I am pretty busy with work and family. I will get back to it, soon or maybe @LemurensReise can find something as the error seems to be reproducible with his mirror.

**Comment by LemurensReise** [comment] 2022-01-14 17:59
With some guidence I will do my best! I have a lack of experience and knowledge of this programming, and MM, so need guidence and help to figure this out.

**Comment by thobach** [comment] 2022-01-16 16:50
https://github.com/thobach/MMM-MicrosoftToDo/pull/70 is now merged into master.

**Comment by LemurensReise** [comment] 2022-01-16 18:53
After reinstalling the module, and adding :
useRelativeDate: true,
I have gaines a check box on the MM, but no text from the app. Still have bad request in the log.

**Comment by thobach** [comment] 2022-01-16 19:03
@LemurensReise This may indicate a misconfiguration in the config.js or Azure portal, or some bad characters in the config.js values. I could review some information if you share your config.js module configuration with only the first and last few characters of the oauth2ClientSecret, oauth2RefreshToken and oauth2ClientId.

**Comment by LemurensReise** [comment] 2022-01-16 19:05
This is my MMM-MicrosoftToDo module in config.js right now:

		{
		module: 'MMM-MicrosoftToDo',
		position: 'top_left',	// This can be any of the regions. Best results in left or right regions.
		header: 'Øvinger', // This is optional
		config: {
		  oauth2ClientSecret: '',
		  oauth2RefreshToken: '',
		  oauth2ClientId: '',
		  listName: 'ovinger', // optional parameter: if not specified displays tasks from default "Tasks" list, if specified will look for a task list with the specified name (exact spelling)
		  // Optional parameter:  see Planned Tasks Configuration
		  plannedTasks: {
			enabled: false
		  },
		  showCheckbox: true, // optional parameter: default value is true and will show a checkbox before each todo list item
		  showDueDate: false, // optional parameter: default value is false and will show the todo list items due date if it exists on the todo list item
		  dateFormat: 'ddd MMM Do [ - ]', //optional parameter: uses moment date format and the default value is 'ddd MMM Do [ - ]'
		  useRelativeDate: true,
		  highlightTagColor: '#E3FF30', // optional parameter: highlight tags (#Tags) in the entry text. value can be a HTML color value
		  hideIfEmpty: false, // optional parameter: default value is false and will show the module also when the todo list is empty
		  maxWidth: 450, // optional parameter: max width in pixel, default value is 450
		  itemLimit: 200, // optional parameter: limit on the number of items to show from the list, default value is 200
		  orderBy: 'createdDate', // optional parameter: 'createdDate' - order results by creation date, 'dueDate' - order results by due date, default value is unordered, ordering by title is not supported anymore in API version 1
		  completeOnClick: true, // optional parameter: default value is false, when set to true complete task when clicking on it
		  refreshSeconds: 60, // optional parameter: every how many seconds should the list be updated from the remote service, default value is 60
		  fade: true, //optional parameter: default value is false. True will fade the list towards the bottom from the point set in the fadePoint parameter
		  fadePoint: 0.5 //optional parameter: decimal value between 0 and 1 sets the point where the fade effect will start,
			// optional parameter: default value is false.  True will display colors for overdue (red), upcoming (orange), and future (green) dates
		}
	  },

**Comment by LemurensReise** [comment] 2022-01-16 19:11
@thobach this is my config.js file right now

		{
		module: 'MMM-MicrosoftToDo',
		position: 'top_left',	// This can be any of the regions. Best results in left or right regions.
		header: 'Øvinger', // This is optional
		config: {
		  oauth2ClientSecret: 'Kp-7***er-p6E',
		  oauth2RefreshToken: 'M.R3_BAY.-CbqD***k932jn',
		  oauth2ClientId: '908b9***49b7',
		  listName: 'ovinger', // optional parameter: if not specified displays tasks from default "Tasks" list, if specified will look for a task list with the specified name (exact spelling)
		  // Optional parameter:  see Planned Tasks Configuration
		  plannedTasks: {
			enabled: false
		  },
		  showCheckbox: true, // optional parameter: default value is true and will show a checkbox before each todo list item
		  showDueDate: false, // optional parameter: default value is false and will show the todo list items due date if it exists on the todo list item
		  dateFormat: 'ddd MMM Do [ - ]', //optional parameter: uses moment date format and the default value is 'ddd MMM Do [ - ]'
		  useRelativeDate: true,
		  highlightTagColor: '#E3FF30', // optional parameter: highlight tags (#Tags) in the entry text. value can be a HTML color value
		  hideIfEmpty: false, // optional parameter: default value is false and will show the module also when the todo list is empty
		  maxWidth: 450, // optional parameter: max width in pixel, default value is 450
		  itemLimit: 200, // optional parameter: limit on the number of items to show from the list, default value is 200
		  orderBy: 'createdDate', // optional parameter: 'createdDate' - order results by creation date, 'dueDate' - order results by due date, default value is unordered, ordering by title is not supported anymore in API version 1
		  completeOnClick: true, // optional parameter: default value is false, when set to true complete task when clicking on it
		  refreshSeconds: 60, // optional parameter: every how many seconds should the list be updated from the remote service, default value is 60
		  fade: true, //optional parameter: default value is false. True will fade the list towards the bottom from the point set in the fadePoint parameter
		  fadePoint: 0.5 //optional parameter: decimal value between 0 and 1 sets the point where the fade effect will start,
			// optional parameter: default value is false.  True will display colors for overdue (red), upcoming (orange), and future (green) dates
		}
	  },

**Comment by LemurensReise** [comment] 2022-01-20 18:32
@thobach 
Does the values look ok? Should I try the whole installation, and set up the Azure-account again? Maybe it's settings in the Azure-account?

**Comment by thobach** [comment] 2022-01-23 13:36
@LemurensReise The syntax looks good, maybe one of the values is invalid (e.g. not existing anymore on the Azure Portal). I improved error logging in last commit https://github.com/thobach/MMM-MicrosoftToDo/commit/9e9ba1a6e5edde5a6be782b5e633a8285b3769f8. Could you please update to the latest version with `git pull` and post the related logs from Magic Mirror? Thanks!

**Comment by LemurensReise** [comment] 2022-01-23 13:46
@thobach 

[23.01.2022 14:45.40.046] [INFO]  Checking git for module: MMM-MicrosoftToDo
[23.01.2022 14:45.40.235] [INFO]  Checking git for module: default
[23.01.2022 14:45.44.552] [ERROR] Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
    status: 400,
    statusText: 'Bad Request',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}

**Comment by thobach** [comment] 2022-01-23 14:00
@LemurensReise The issue seems to be with generating the access token. I suggest to try again the whole installation in the Azure portal and update the `oauth` configuration parameters accordingly. If you like you can also contact me on twitter with a direct message (https://twitter.com/thobach) and I'll let you know my email address to send me screenshots of the Azure portal configuration.

**Comment by thobach** [comment] 2022-01-29 11:53
@magic21nrw Could you please try with the latest version? A number of issues were addressed in the meantime. Thanks!

**Comment by magic21nrw** [comment] 2022-01-29 12:07
@thobach 

Login and Tokens are correct as with the old version it is working flawless.
Unfortunately no change but the logging is more verbose now:



Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]: [29.01.2022 12:03.56.475] [ERROR] Response {
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:   size: 0,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:   timeout: 0,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:   [Symbol(Body internals)]: {
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:     body: Gunzip {
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _writeState: [Uint32Array],
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _readableState: [ReadableState],
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _events: [Object: null prototype],
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _eventsCount: 5,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _maxListeners: undefined,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _writableState: [WritableState],
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       allowHalfOpen: true,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       bytesWritten: 0,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _handle: [Zlib],
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _outBuffer: <Buffer 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 e0 b6 21 06 00 00 00 00 e0 b6 21 06 00 00 00 00 20 52 65 71 75 65 73 74 0d 0a 43 61 63 68 65 2d 43 6f ... 16334 more bytes>,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _outOffset: 0,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _chunkSize: 16384,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _defaultFlushFlag: 2,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _finishFlushFlag: 2,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _defaultFullFlushFlag: 3,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _info: undefined,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _maxOutputLength: 4294967296,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _level: -1,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       _strategy: 0,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       [Symbol(kCapture)]: false,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       [Symbol(kCallback)]: null,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:       [Symbol(kError)]: null
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:     },
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:     disturbed: false,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:     error: null
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:   },
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:   [Symbol(Response internals)]: {
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:     url: 'https://graph.microsoft.com/v1.0/me/todo/lists/?$top=200&$filter=displayName%20eq%20%27Kathrin%26Daniel%20To%20Do%20Spiegel%27',
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:     status: 400,
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:     statusText: 'Bad Request',
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:     headers: Headers { [Symbol(map)]: [Object: null prototype] },
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:     counter: 0
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]:   }
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]: }
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]: [29.01.2022 12:03.56.476] [ERROR] [MMM-MicrosoftToDo]: fetchList https://graph.microsoft.com/v1.0/me/todo/lists/?$top=200&$filter=displayName%20eq%20%27Kathrin%26Daniel%20To%20Do%20Spiegel%27
Jan 29 12:03:56 MagicMirrorServer runserver.sh[736]: [29.01.2022 12:03.56.476] [ERROR] [MMM-MicrosoftToDo]: Error: checkFetchStatus failed with status 'Bad Request' {"size":0,"timeout":0}
Jan 29 12:03:57 MagicMirrorServer systemd[986]: tracker-extract.service: Succeeded.

**Comment by thobach** [comment] 2022-01-29 12:20
@magic21nrw The issue seems to be with the list name in the search. In particular the `&` sign. Can you try to replace that from the listName with a space character, or rename the list?

**Comment by magic21nrw** [comment] 2022-01-29 12:31
@thobach 

This solved the problem. Thanks for finding it out with your logging on the API.

I think, as it worked in the old version one should at lease mention in the manual, that the & sign is not allowed or in the request properly escape that character. I mean with the old version it was possible so there should be a way around it technically.

Daniel

**Comment by spyder007** [comment] 2022-01-29 12:31
If you are using planned tasks, use the includelists config under that setting, and remove your list name.

Incudelists is a strong array where the strings are regex values or an exact list name.

**Comment by thobach** [comment] 2022-02-28 10:13
@spyder007 Thanks for your offer to expand the documentation, please let me know when I can close the issue. Thanks!

**Comment by prysme01** [comment] 2022-03-11 14:43
@thobach you were right, my bad :) now it is working.

**Closed** 2022-03-20 13:31 UTC

**Comment by jobo84** [comment] 2023-05-23 05:24
Im experiencing the same problem, Bad request error. I tried clean install two times without success.
